volumes:
  postgres-data:
    driver: local
  mail-data:
    driver: local

services:
#  app-web:
#    build:
#      context: ./docker/app-web
#      args:
#        CONTAINERS_TIMEZONE: ${CONTAINERS_TIMEZONE}
#        CONTAINERS_LANG: ${CONTAINERS_LANG}
#        WEB_USER_NAME: ${WEB_USER_NAME}
#        WEB_USER_UID: ${WEB_USER_UID}
#        WEB_USER_GROUP: ${WEB_USER_GROUP}
#        WEB_USER_GID: ${WEB_USER_GID}
#        WEB_USER_SHELL: ${WEB_USER_SHELL:-/usr/sbin/nologin}
#        ENABLE_XDEBUG: ${ENABLE_XDEBUG:-false}
#    environment:
#      APACHE_RUN_USER : ${WEB_USER_NAME}
#      APACHE_RUN_GROUP : ${WEB_USER_GROUP}
#    volumes:
#      - type: bind
#        source: ./app
#        target: /var/www/html/app
#    ports:
#      - target: 80
#        published: 8080
#        protocol: tcp
#        mode: host
#    logging:
#      driver: json-file
#      options:
#        max-size: ${LOG_MAX_SIZE:-10m}
#        max-file: ${LOG_MAX_FILE:-5}

  app:
    build:
      context: ./docker/app
      args:
        CONTAINERS_TIMEZONE: ${CONTAINERS_TIMEZONE}
        CONTAINERS_LANG: ${CONTAINERS_LANG}
        WEB_USER_NAME: ${WEB_USER_NAME}
        WEB_USER_UID: ${WEB_USER_UID}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_USER_GID: ${WEB_USER_GID}
        WEB_USER_SHELL: ${WEB_USER_SHELL:-/usr/sbin/nologin}
        ENABLE_XDEBUG: ${ENABLE_XDEBUG:-false}
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html/app
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-5}

  web:
    build:
      context: ./docker/web
      args:
        CONTAINERS_TIMEZONE: ${CONTAINERS_TIMEZONE}
        CONTAINERS_LANG: ${CONTAINERS_LANG}
        WEB_USER_NAME: ${WEB_USER_NAME}
        WEB_USER_UID: ${WEB_USER_UID}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_USER_GID: ${WEB_USER_GID}
        WEB_USER_SHELL: ${WEB_USER_SHELL:-/usr/sbin/nologin}
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html/app
    depends_on:
      - app
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-5}

  db:
    build:
      context: ./docker/db
      args:
        CONTAINERS_TIMEZONE: ${CONTAINERS_TIMEZONE}
        CONTAINERS_LANG: ${CONTAINERS_LANG}
    command: >
      postgres
      -c log_destination=stderr
      -c log_statement=all
      -c log_connections=on
      -c log_disconnections=on
      -c log_min_duration_statement=1000
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-5}

  kvs:
    build:
      context: ./docker/kvs
      args:
        CONTAINERS_TIMEZONE: ${CONTAINERS_TIMEZONE}
        REDIS_AUTH_PASS: ${REDIS_AUTH_PASS}
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    sysctls:
      net.core.somaxconn: 511
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-5}

  smtp:
    image: mailhog/mailhog:v1.0.1
    ports:
      - target: 8025
        published: 8025
        protocol: tcp
        mode: host
      - target: 1025
        published: 1025
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: mail-data
        target: /tmp
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-5}