version: "3.7"

volumes:
  mysql-data:
    driver: local
  mail-data:
    driver: local

services:
#  app-web:
#    build:
#      context: ./docker/app-web
#      args:
#        CONTAINERS_TIMEZONE: ${CONTAINERS_TIMEZONE}
#        CONTAINERS_LANG: ${CONTAINERS_LANG}
#        WEB_USER_NAME: ${WEB_USER_NAME}
#        WEB_USER_UID: ${WEB_USER_UID}
#        WEB_USER_GROUP: ${WEB_USER_GROUP}
#        WEB_USER_GID: ${WEB_USER_GID}
#        WEB_USER_SHELL: ${WEB_USER_SHELL:-/usr/sbin/nologin}
#        ENABLE_XDBUG: ${ENABLE_XDBUG:-false}
#    environment:
#      APACHE_RUN_USER : ${WEB_USER_NAME}
#      APACHE_RUN_GROUP : ${WEB_USER_GROUP}
#    volumes:
#      - type: bind
#        source: ./app
#        target: /var/www/html/app
#    ports:
#      - target: 80
#        published: 8080
#        protocol: tcp
#        mode: host

  app:
    build:
      context: ./docker/app
      args:
        CONTAINERS_TIMEZONE: ${CONTAINERS_TIMEZONE}
        CONTAINERS_LANG: ${CONTAINERS_LANG}
        WEB_USER_NAME: ${WEB_USER_NAME}
        WEB_USER_UID: ${WEB_USER_UID}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_USER_GID: ${WEB_USER_GID}
        WEB_USER_SHELL: ${WEB_USER_SHELL:-/usr/sbin/nologin}
        ENABLE_XDBUG: ${ENABLE_XDBUG:-false}
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html/app

  web:
    build:
      context: ./docker/web
      args:
        CONTAINERS_TIMEZONE: ${CONTAINERS_TIMEZONE}
        CONTAINERS_LANG: ${CONTAINERS_LANG}
        WEB_USER_NAME: ${WEB_USER_NAME}
        WEB_USER_UID: ${WEB_USER_UID}
        WEB_USER_GROUP: ${WEB_USER_GROUP}
        WEB_USER_GID: ${WEB_USER_GID}
        WEB_USER_SHELL: ${WEB_USER_SHELL:-/usr/sbin/nologin}
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html/app
    depends_on:
      - app
  
  db:
    build:
      context: ./docker/db
      args:
        CONTAINERS_TIMEZONE: ${CONTAINERS_TIMEZONE}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DEFAULT_DB: ${MYSQL_DEFAULT_DB}
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
        volume:
          nocopy: true

  kvs:
    build:
      context: ./docker/kvs
      args:
        CONTAINERS_TIMEZONE: ${CONTAINERS_TIMEZONE}
        REDIS_AUTH_PASS: ${REDIS_AUTH_PASS}
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    sysctls:
      net.core.somaxconn: 511

  smtp:
    image: mailhog/mailhog:v1.0.1
    ports:
      - target: 8025
        published: 8025
        protocol: tcp
        mode: host
      - target: 1025
        published: 1025
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: mail-data
        target: /tmp