
#!/bin/sh

mysql -u root --password="${MYSQL_ROOT_PASSWORD}" << EOT
  CREATE DATABASE IF NOT EXISTS ${MYSQL_DEFAULT_DB} DEFAULT CHARACTER SET utf8mb4;
  GRANT ALL ON ${MYSQL_DEFAULT_DB}.* TO '${MYSQL_USER}'@'%';
  DELETE FROM mysql.user WHERE User='';
  DROP DATABASE IF EXISTS test;
  FLUSH PRIVILEGES;
EOT